package com.va.dsm.testcases;// Generated by Selenium IDE
import com.va.dsm.util.LoadDriver;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.*;

public class MailboxForwardMultipleCCDattachmentsTest extends LoadDriver {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeTest
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterTest
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void mailboxForwardMultipleCCDattachments() {
        // Test name: Mailbox -  Forward Multiple CCD attachments
        // Step # | name | target | value
        // 1 | open | /inbox |
        driver.get("https://test1.direct.va.gov/inbox/inbox");

        driver.manage().window().maximize();
        // 3 | click | linkText=ORIGINAL MESSAGE FOR FORWARD |
        driver.findElement(By.linkText("ORIGINAL MESSAGE FOR FORWARD")).click();
        // 4 | click | css=.button:nth-child(3) > img |
        driver.findElement(By.cssSelector(".button:nth-child(3) > img")).click();
        // 5 | click | id=token-input-message_to |
        driver.findElement(By.id("token-input-message_to")).click();
        // 6 | type | id=token-input-message_to | john.egan4@vademo.stagingcernerdirect.com;
        driver.findElement(By.id("token-input-message_to")).sendKeys("john.egan4@vademo.stagingcernerdirect.com;");
        // 7 | sendKeys | id=token-input-message_to | ${KEY_ENTER}
        driver.findElement(By.id("token-input-message_to")).sendKeys(Keys.ENTER);
        // 8 | type | id=message_subject | Forward Multiple CCD attachments
        driver.findElement(By.id("message_subject")).sendKeys("Forward Multiple CCD attachments");
        // 9 | click | id=attach-patient-document |
        driver.findElement(By.id("attach-patient-document")).click();
        // 10 | type | id=given-name-field | nwhinone
        driver.findElement(By.id("given-name-field")).sendKeys("nwhinone");
        // 11 | type | id=family-name-field | nwhinzzztestpatient
        driver.findElement(By.id("family-name-field")).sendKeys("nwhinzzztestpatient");
        // 12 | click | id=area_number |
        driver.findElement(By.id("area_number")).click();
        // 13 | type | id=area_number | 666
        driver.findElement(By.id("area_number")).sendKeys("666");
        // 14 | click | id=group_number |
        driver.findElement(By.id("group_number")).click();
        // 15 | type | id=group_number | 10
        driver.findElement(By.id("group_number")).sendKeys("10");
        // 16 | click | id=serial_number |
        driver.findElement(By.id("serial_number")).click();
        // 17 | type | id=serial_number | 0001
        driver.findElement(By.id("serial_number")).sendKeys("0001");
        // 18 | click | id=patient_lookup_form_button_find_matching |
        driver.findElement(By.id("patient_lookup_form_button_find_matching")).click();
        // 19 | click | name=patient_id |
        driver.findElement(By.name("patient_id")).click();
        // 20 | click | css=.ui-dialog:nth-child(12) .ui-button:nth-child(1) |
        driver.findElement(By.cssSelector(".ui-dialog:nth-child(12) .ui-button:nth-child(1)")).click();
        // 21 | click | id=send_btn |
        driver.findElement(By.id("send_btn")).click();
        // 22 | click | css=.ui-dialog-buttonset > .ui-button:nth-child(3) |
        driver.findElement(By.cssSelector(".ui-dialog-buttonset > .ui-button:nth-child(3)")).click();
        // 23 | click | id=attach-patient-document |
        driver.findElement(By.id("attach-patient-document")).click();
        // 24 | type | id=given-name-field | nwhintwo
        driver.findElement(By.id("given-name-field")).sendKeys("nwhintwo");
        // 25 | type | id=family-name-field | nwhinzzztestpatient
        driver.findElement(By.id("family-name-field")).sendKeys("nwhinzzztestpatient");
        // 26 | click | name=social_security_number[area_number] |
        driver.findElement(By.name("social_security_number[area_number]")).click();
        // 27 | type | name=social_security_number[area_number] | 666
        driver.findElement(By.name("social_security_number[area_number]")).sendKeys("666");
        // 28 | click | name=social_security_number[group_number] |
        driver.findElement(By.name("social_security_number[group_number]")).click();
        // 29 | type | name=social_security_number[group_number] | 10
        driver.findElement(By.name("social_security_number[group_number]")).sendKeys("10");
        // 30 | type | name=social_security_number[serial_number] | 0002
        driver.findElement(By.name("social_security_number[serial_number]")).sendKeys("0002");
        // 31 | click | id=patient_lookup_form_button_find_matching |
        driver.findElement(By.id("patient_lookup_form_button_find_matching")).click();
        // 32 | click | name=patient_id |
        driver.findElement(By.name("patient_id")).click();
        // 33 | click | css=.ui-dialog:nth-child(12) .ui-button:nth-child(1) |
        driver.findElement(By.cssSelector(".ui-dialog:nth-child(12) .ui-button:nth-child(1)")).click();
        // 34 | click | id=send_btn |
        driver.findElement(By.id("send_btn")).click();
        // 35 | click | css=.ui-dialog:nth-child(10) .ui-button:nth-child(1) |
        driver.findElement(By.cssSelector(".ui-dialog:nth-child(10) .ui-button:nth-child(1)")).click();
        // 36 | verifyText | css=.noty_text:nth-child(1) | Message successfully sent.
        assertThat(driver.findElement(By.cssSelector(".noty_text:nth-child(1)")).getText(), is("Message successfully sent."));
    }
}
